import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ModalContextProvider from "@/context/ModalContext";
import PaginationContextProvider from "@/context/PaginationContext";
import ArtistContextProvider from "@/context/ArtistContext";
const poppins = Poppins({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web artists",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${poppins} bg-dark01 `}>
        <PaginationContextProvider>
          <ArtistContextProvider>
            <ModalContextProvider>{children}</ModalContextProvider>
          </ArtistContextProvider>
        </PaginationContextProvider>
      </body>
    </html>
  );
}
